package vgi;

import com.mxgraph.model.mxCell;
import java.util.Hashtable;
import java.util.Iterator;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Automata_properties.java
 *
 * Created on 2012/1/6, 下午 04:01:27
 */
/**
 *
 * @author bl606
 */
public class Automata_properties extends javax.swing.JPanel {

    /** Creates new form Automata_properties */
   public Automata_properties(Automata automata) {
        initComponents();
        this.automata = automata;
        this.cellTable = cellTable;
        
        if (automata != null) {
            showStates();
            showTransitions();
            showInitials();
            showFinals();
        }
    }
    
    private void showStates() {
        stateTextField.setText(
                Integer.toString(automata.getAllStates().size()));

        Iterator<State> iterator = this.automata.getAllStates().iterator();
        while (iterator.hasNext()) {
            State state = iterator.next();
            stateComboBox.addItem(state.getName());
        }
    }
    
    private void showTransitions() {
        transitionTextField.setText(
                Integer.toString(automata.getAllTransitions().size()));
    }
    
    private void showInitials() {
        this.initialTextField.setText(
                Integer.toString(automata.getAllInitialStates().size()));
    }
    
    private void showFinals() {
        this.finalTextField.setText(
                Integer.toString(automata.getAllFinalStates().size()));
    }
    
    private Automata automata = null;
    Hashtable<mxCell, State> cellTable;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        stateLabel = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        transitionLabel = new javax.swing.JLabel();
        transitionTextField = new javax.swing.JTextField();
        initialLabel = new javax.swing.JLabel();
        initialTextField = new javax.swing.JTextField();
        finalLabel = new javax.swing.JLabel();
        finalTextField = new javax.swing.JTextField();
        stateComboBox = new javax.swing.JComboBox();
        transitionComboBox = new javax.swing.JComboBox();
        initialComboBox = new javax.swing.JComboBox();
        finalComboBox = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridBagLayout());

        stateLabel.setText("States :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(stateLabel, gridBagConstraints);

        stateTextField.setColumns(5);
        stateTextField.setEditable(false);
        stateTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        stateTextField.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(stateTextField, gridBagConstraints);

        transitionLabel.setText("Transitions :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(transitionLabel, gridBagConstraints);

        transitionTextField.setColumns(5);
        transitionTextField.setEditable(false);
        transitionTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        transitionTextField.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(transitionTextField, gridBagConstraints);

        initialLabel.setText("Initial states :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(initialLabel, gridBagConstraints);

        initialTextField.setColumns(5);
        initialTextField.setEditable(false);
        initialTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        initialTextField.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(initialTextField, gridBagConstraints);

        finalLabel.setText("Final states :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(finalLabel, gridBagConstraints);

        finalTextField.setColumns(5);
        finalTextField.setEditable(false);
        finalTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        finalTextField.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(finalTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        add(stateComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        add(transitionComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.1;
        add(initialComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.1;
        add(finalComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox finalComboBox;
    private javax.swing.JLabel finalLabel;
    private javax.swing.JTextField finalTextField;
    private javax.swing.JComboBox initialComboBox;
    private javax.swing.JLabel initialLabel;
    private javax.swing.JTextField initialTextField;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JComboBox transitionComboBox;
    private javax.swing.JLabel transitionLabel;
    private javax.swing.JTextField transitionTextField;
    // End of variables declaration//GEN-END:variables
}
