package vgi;


import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * createAutomataDialog.java
 *
 * Created on 2011/12/10, 下午 01:12:26
 */
/**
 *
 * @author wkren
 */
public class CreateAutomataDialog extends javax.swing.JDialog {

    /** Creates new form createAutomataDialog */
    public CreateAutomataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
		this.FMPButton.setVisible(false);
        this.monoidAlphabetPanel1.setVisible(false);
        this.createFlag = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SemiringTypeButtonGroup = new javax.swing.ButtonGroup();
        SemiringSetButtonGroup = new javax.swing.ButtonGroup();
        SemiringOperationButtonGroup = new javax.swing.ButtonGroup();
        MonoidTypeButtonGroup = new javax.swing.ButtonGroup();
        semiringSetOperationbuttonGroup = new javax.swing.ButtonGroup();
        semiringPanel = new javax.swing.JPanel();
        semiringSetOperationPanel = new javax.swing.JPanel();
        semiringBooleanRadioButton = new javax.swing.JRadioButton();
        semiringIntegerRadioButton = new javax.swing.JRadioButton();
        semiringRationalRadioButton = new javax.swing.JRadioButton();
        semiringRealRadioButton = new javax.swing.JRadioButton();
        semiringF2RadioButton = new javax.swing.JRadioButton();
        semiringMinTropicalRadioButton = new javax.swing.JRadioButton();
        semiringMaxTropicalRadioButton = new javax.swing.JRadioButton();
        monoidPanel = new javax.swing.JPanel();
        monoidSymbolPanel = new javax.swing.JPanel();
        monoidAlphabetPanel = new javax.swing.JPanel();
        monoidAlphabetComboBox = new javax.swing.JComboBox();
        subAlphabetPanel = new javax.swing.JPanel();
        addAlphabetButton = new javax.swing.JButton();
        delAlphabetButton = new javax.swing.JButton();
        monoidAlphabetPanel1 = new javax.swing.JPanel();
        monoidAlphabetComboBox1 = new javax.swing.JComboBox();
        subAlphabetPanel1 = new javax.swing.JPanel();
        addAlphabetButton1 = new javax.swing.JButton();
        delAlphabetButton1 = new javax.swing.JButton();
        monoidZeroSymbolPanel = new javax.swing.JPanel();
        monoidZeroSymbolTextField = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        okCanelPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        defaultButton = new javax.swing.JButton();
        FMPButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Type");

        semiringPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Semiring"));
        semiringPanel.setLayout(new java.awt.GridLayout(1, 0));

        semiringSetOperationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Set&Operation"));
        semiringSetOperationPanel.setLayout(new javax.swing.BoxLayout(semiringSetOperationPanel, javax.swing.BoxLayout.PAGE_AXIS));

        semiringSetOperationbuttonGroup.add(semiringBooleanRadioButton);
        semiringBooleanRadioButton.setText("Boolean");
        semiringBooleanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringBooleanRadioButton);

        semiringSetOperationbuttonGroup.add(semiringIntegerRadioButton);
        semiringIntegerRadioButton.setText("Integer");
        semiringIntegerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringIntegerRadioButton);

        semiringSetOperationbuttonGroup.add(semiringRationalRadioButton);
        semiringRationalRadioButton.setText("Rational");
        semiringRationalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringRationalRadioButton);

        semiringSetOperationbuttonGroup.add(semiringRealRadioButton);
        semiringRealRadioButton.setText("Real");
        semiringRealRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringRealRadioButton);

        semiringSetOperationbuttonGroup.add(semiringF2RadioButton);
        semiringF2RadioButton.setText("Two Element Field");
        semiringF2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringF2RadioButton);

        semiringSetOperationbuttonGroup.add(semiringMinTropicalRadioButton);
        semiringMinTropicalRadioButton.setText("Min Tropical");
        semiringMinTropicalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringMinTropicalRadioButton);

        semiringSetOperationbuttonGroup.add(semiringMaxTropicalRadioButton);
        semiringMaxTropicalRadioButton.setText("Max Tropical");
        semiringMaxTropicalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetOperationRadioButtonActionPerformed(evt);
            }
        });
        semiringSetOperationPanel.add(semiringMaxTropicalRadioButton);

        semiringPanel.add(semiringSetOperationPanel);

        getContentPane().add(semiringPanel, java.awt.BorderLayout.PAGE_START);

        monoidPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Monoid"));
        monoidPanel.setLayout(new java.awt.GridLayout(1, 0));

        monoidSymbolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Symbol"));
        monoidSymbolPanel.setLayout(new java.awt.GridLayout(2, 0));

        monoidAlphabetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Alphabet"));
        monoidAlphabetPanel.setLayout(new java.awt.GridLayout(1, 0));

        monoidAlphabetComboBox.setEditable(true);
        monoidAlphabetPanel.add(monoidAlphabetComboBox);

        subAlphabetPanel.setLayout(new java.awt.GridLayout(2, 1));

        addAlphabetButton.setText("add");
        addAlphabetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monoidAlphabetAdd(evt);
            }
        });
        subAlphabetPanel.add(addAlphabetButton);

        delAlphabetButton.setText("delete");
        delAlphabetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monoidDelAlphabetActionPerformed(evt);
            }
        });
        subAlphabetPanel.add(delAlphabetButton);

        monoidAlphabetPanel.add(subAlphabetPanel);

        monoidSymbolPanel.add(monoidAlphabetPanel);

        monoidAlphabetPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alphabet"));
        monoidAlphabetPanel1.setLayout(new java.awt.GridLayout(1, 0));

        monoidAlphabetComboBox1.setEditable(true);
        monoidAlphabetPanel1.add(monoidAlphabetComboBox1);

        subAlphabetPanel1.setLayout(new java.awt.GridLayout(2, 1));

        addAlphabetButton1.setText("add");
        addAlphabetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlphabetButton1monoidAlphabetAdd(evt);
            }
        });
        subAlphabetPanel1.add(addAlphabetButton1);

        delAlphabetButton1.setText("delete");
        delAlphabetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAlphabetButton1monoidDelAlphabetActionPerformed(evt);
            }
        });
        subAlphabetPanel1.add(delAlphabetButton1);

        monoidAlphabetPanel1.add(subAlphabetPanel1);

        monoidSymbolPanel.add(monoidAlphabetPanel1);

        monoidPanel.add(monoidSymbolPanel);

        monoidZeroSymbolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Zero Symbol"));
        monoidZeroSymbolPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        monoidZeroSymbolTextField.setText("0");
        monoidZeroSymbolPanel.add(monoidZeroSymbolTextField);

        monoidPanel.add(monoidZeroSymbolPanel);

        getContentPane().add(monoidPanel, java.awt.BorderLayout.CENTER);

        ButtonPanel.setLayout(new java.awt.BorderLayout());

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        okCanelPanel.add(cancelButton);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okCanelPanel.add(okButton);

        ButtonPanel.add(okCanelPanel, java.awt.BorderLayout.EAST);

        defaultButton.setText("Default");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(defaultButton);

        FMPButton.setText("FMP");
        FMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMPButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(FMPButton);

        ButtonPanel.add(buttonPanel, java.awt.BorderLayout.WEST);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monoidAlphabetAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monoidAlphabetAdd
        // TODO add your handling code here:
        monoidAlphabetComboBox.addItem(monoidAlphabetComboBox.getSelectedItem());
    }//GEN-LAST:event_monoidAlphabetAdd

    private void monoidDelAlphabetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monoidDelAlphabetActionPerformed
        // TODO add your handling code here:
        monoidAlphabetComboBox.removeItem(monoidAlphabetComboBox.getSelectedItem());
    }//GEN-LAST:event_monoidDelAlphabetActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        createFlag = false;
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
//        if (!((semiringZeroSymbolTextField.getText().equals("")) ||
//             (semiringIdentitySymbolTextField.getText().equals("")) ||
//             (semiringType == null) || (semiringSet == null) ||
//             (semiringOperation == null))) {
//            Semiring semiring = new Semiring(semiringZeroSymbolTextField.getText(),
//                                           semiringIdentitySymbolTextField.getText(),
//                                           semiringType, semiringSet,
//                                           semiringOperation, "", null, null);
//            Monoid monoid = new Monoid(monoidZeroSymbolTextField.getText(), 
//                                      monoidAlphabetComboBox.getModel().getSize(), 
//                                      monoidAlphabetComboBox.getModel(), 
//                                      0, null);
//            this.setVisible(false);
//            createFlag = true;
//        }
        if (!(tafKitSemiring == null)) {
            this.setVisible(false);
            createFlag = true;
        }
        else {
            System.out.println("some options are empty");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        // TODO add your handling code here:
        this.monoidAlphabetPanel1.setVisible(false);
        this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.B_BOOLEAN;
        this.semiringBooleanRadioButton.setSelected(true);
        this.monoidAlphabetComboBox.addItem("a");
        this.monoidAlphabetComboBox.addItem("b");
        this.semiringRationalRadioButton.setEnabled(true);
        this.semiringRealRadioButton.setEnabled(true);
        this.semiringF2RadioButton.setEnabled(true);
        this.semiringMaxTropicalRadioButton.setEnabled(true);
        this.semiringMinTropicalRadioButton.setEnabled(true);
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void semiringSetOperationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semiringSetOperationRadioButtonActionPerformed
        // TODO add your handling code here:
        String cmd = evt.getActionCommand();
        if (cmd.equals("Boolean")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.B_BOOLEAN;
        }
        else if (cmd.equals("Integer")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.Z_INTEGER;
        }
        else if (cmd.equals("Rational")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.Q_RATIONAL;
        }
        else if (cmd.equals("Real")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.R_REAL;
        }
        else if (cmd.equals("Two Element Field")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.F2_TWO_ELEMENT_FIELD;
        }
        else if (cmd.equals("Min Tropical")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.ZMIN_MIN_TROPICAL;
        }
        else if (cmd.equals("Max Tropical")) {
            this.tafKitSemiring = TAFKitInterface.AutomataType.Semiring.ZMAX_MAX_TROPICAL;
        }
    }//GEN-LAST:event_semiringSetOperationRadioButtonActionPerformed

    private void FMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMPButtonActionPerformed
        // TODO add your handling code here:
        this.defaultButtonActionPerformed(evt);
        this.semiringRationalRadioButton.setEnabled(false);
        this.semiringRealRadioButton.setEnabled(false);
        this.semiringF2RadioButton.setEnabled(false);
        this.semiringMaxTropicalRadioButton.setEnabled(false);
        this.semiringMinTropicalRadioButton.setEnabled(false);
        this.monoidAlphabetPanel1.setVisible(true);
    }//GEN-LAST:event_FMPButtonActionPerformed

    private void addAlphabetButton1monoidAlphabetAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlphabetButton1monoidAlphabetAdd
        // TODO add your handling code here:
        monoidAlphabetComboBox1.addItem(monoidAlphabetComboBox.getSelectedItem());
    }//GEN-LAST:event_addAlphabetButton1monoidAlphabetAdd

    private void delAlphabetButton1monoidDelAlphabetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAlphabetButton1monoidDelAlphabetActionPerformed
        // TODO add your handling code here:
        monoidAlphabetComboBox1.removeItem(monoidAlphabetComboBox.getSelectedItem());
    }//GEN-LAST:event_delAlphabetButton1monoidDelAlphabetActionPerformed

	public AutomataInterface.Alphabet getAlphabet() {
		AutomataInterface.Alphabet alphabet = new AutomataInterface.Alphabet();
		alphabet.dataType = TAFKitInterface.AutomataType.AlphabetDataType.CHAR;
		int count = this.monoidAlphabetComboBox.getItemCount();
		this.monoidAlphabet = new ArrayList(count);
		for (int index = 0; index < count; index++) {
			this.monoidAlphabet.add(this.monoidAlphabetComboBox.getItemAt(index));
		}
		alphabet.allSymbols = this.monoidAlphabet;
		alphabet.identitySymbol = new Character('1');
		return alphabet;
	}

	public AutomataInterface.Weight getWeight() {
		AutomataInterface.Weight weight = new AutomataInterface.Weight();
		weight.semiring = this.tafKitSemiring;
		return weight;
	}

	public AutomataInterface.WritingData getWritingData() {
		AutomataInterface.WritingData writingData = new AutomataInterface.WritingData();
		writingData.closePar = new Character(')');
		writingData.openPar = new Character('(');
		writingData.plusSym = new Character('+');
		writingData.spacesSym = new Character(' ');
		writingData.starSym = new Character('*');
		writingData.timesSym = new Character('.');
		writingData.weightClosing = new Character('}');
		writingData.weightOpening = new Character('{');
		this.monoidZeroSymbol = this.monoidZeroSymbolTextField.getText();
		if ((this.monoidZeroSymbol == null) || (this.monoidZeroSymbol.isEmpty())) {
			writingData.zeroSym = new Character('e');
		} else {
			writingData.zeroSym = new Character(this.monoidZeroSymbol.charAt(0));
		}
		return writingData;
	}

    public boolean isCreated() {
        return createFlag;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CreateAutomataDialog dialog = new CreateAutomataDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private TAFKitInterface.AutomataType.Semiring tafKitSemiring;
    private String semiringZeroSymbol;
    private String semiringIdentitySymbol;
    private String monoidZeroSymbol;
    private ArrayList monoidAlphabet;
    private boolean createFlag;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel ButtonPanel;
    javax.swing.JButton FMPButton;
    javax.swing.ButtonGroup MonoidTypeButtonGroup;
    javax.swing.ButtonGroup SemiringOperationButtonGroup;
    javax.swing.ButtonGroup SemiringSetButtonGroup;
    javax.swing.ButtonGroup SemiringTypeButtonGroup;
    javax.swing.JButton addAlphabetButton;
    javax.swing.JButton addAlphabetButton1;
    javax.swing.JPanel buttonPanel;
    javax.swing.JButton cancelButton;
    javax.swing.JButton defaultButton;
    javax.swing.JButton delAlphabetButton;
    javax.swing.JButton delAlphabetButton1;
    javax.swing.JComboBox monoidAlphabetComboBox;
    javax.swing.JComboBox monoidAlphabetComboBox1;
    javax.swing.JPanel monoidAlphabetPanel;
    javax.swing.JPanel monoidAlphabetPanel1;
    javax.swing.JPanel monoidPanel;
    javax.swing.JPanel monoidSymbolPanel;
    javax.swing.JPanel monoidZeroSymbolPanel;
    javax.swing.JTextField monoidZeroSymbolTextField;
    javax.swing.JButton okButton;
    javax.swing.JPanel okCanelPanel;
    javax.swing.JRadioButton semiringBooleanRadioButton;
    javax.swing.JRadioButton semiringF2RadioButton;
    javax.swing.JRadioButton semiringIntegerRadioButton;
    javax.swing.JRadioButton semiringMaxTropicalRadioButton;
    javax.swing.JRadioButton semiringMinTropicalRadioButton;
    javax.swing.JPanel semiringPanel;
    javax.swing.JRadioButton semiringRationalRadioButton;
    javax.swing.JRadioButton semiringRealRadioButton;
    javax.swing.JPanel semiringSetOperationPanel;
    javax.swing.ButtonGroup semiringSetOperationbuttonGroup;
    javax.swing.JPanel subAlphabetPanel;
    javax.swing.JPanel subAlphabetPanel1;
    // End of variables declaration//GEN-END:variables
}
