package vgi;

import com.mxgraph.model.mxCell;
import com.mxgraph.view.mxGraph;
import javax.swing.JComboBox;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * edge_properties.java
 *
 * Created on 2012/1/6, 下午 03:59:32
 */
/**
 *
 * @author bl606
 */
public class edge_properties extends javax.swing.JPanel {

    /** Creates new form edge_properties */
    public edge_properties(mxGraph graph, mxCell cell) {
        
        _graph=graph;
        _cell=cell;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        label_label = new javax.swing.JLabel();
        weight_label = new javax.swing.JLabel();
        Label_TextField1 = new javax.swing.JTextField();
        Weight_TextField2 = new javax.swing.JTextField();
        style_label = new javax.swing.JLabel();
        Style_ComboBox = new javax.swing.JComboBox();
        style_label1 = new javax.swing.JLabel();
        End_StyleComboBox = new javax.swing.JComboBox();

        jLabel3.setText("jLabel3");

        setPreferredSize(new java.awt.Dimension(325, 362));
        setLayout(new java.awt.GridBagLayout());

        label_label.setText("Label :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(label_label, gridBagConstraints);

        weight_label.setText("Weight :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(weight_label, gridBagConstraints);

        Label_TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Label_TextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(Label_TextField1, gridBagConstraints);

        Weight_TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Weight_TextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(Weight_TextField2, gridBagConstraints);

        style_label.setText("Start_Style :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(style_label, gridBagConstraints);

        Style_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "classic", "block", "open", "oval", "diamond" }));
        Style_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Style_ComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(Style_ComboBox, gridBagConstraints);

        style_label1.setText("End_Style :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(style_label1, gridBagConstraints);

        End_StyleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "classic", "block", "open", "oval", "diamond" }));
        End_StyleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                End_StyleComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(End_StyleComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void Label_TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Label_TextField1ActionPerformed
// TODO add your handling code here:
    Label = (String)Label_TextField1.getText();
}//GEN-LAST:event_Label_TextField1ActionPerformed

private void Weight_TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Weight_TextField2ActionPerformed
// TODO add your handling code here:
    Weight = (String)Weight_TextField2.getText();
}//GEN-LAST:event_Weight_TextField2ActionPerformed

private void Style_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Style_ComboBoxActionPerformed
// TODO add your handling code here:
    JComboBox cb = (JComboBox)evt.getSource();
    Style = "startArrow=" + ((String)cb.getSelectedItem()).toLowerCase();
    Object[] objects = new Object[1];
    objects[0]=_cell;
    _graph.setCellStyle(Style, objects );
    
}//GEN-LAST:event_Style_ComboBoxActionPerformed

private void End_StyleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_End_StyleComboBoxActionPerformed
// TODO add your handling code here:
    JComboBox cb = (JComboBox)evt.getSource();
    Style = "endArrow=" + ((String)cb.getSelectedItem()).toLowerCase();
    Object[] objects = new Object[1];
    objects[0]=_cell;
    _graph.setCellStyle(Style, objects );
}//GEN-LAST:event_End_StyleComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox End_StyleComboBox;
    private javax.swing.JTextField Label_TextField1;
    private javax.swing.JComboBox Style_ComboBox;
    private javax.swing.JTextField Weight_TextField2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_label;
    private javax.swing.JLabel style_label;
    private javax.swing.JLabel style_label1;
    private javax.swing.JLabel weight_label;
    // End of variables declaration//GEN-END:variables
    private String Label;
    private String Weight;
    
    private String Style;
    private mxCell _cell;
    private mxGraph _graph;
}
