package event;

/**
 * This class is used to classify the event which is invoked by user.
 * A high level event.
 *
 * @author rasielchang
 */
public enum UserEventConstants {

    NOTHING,
    UNKNOW,
    
    /* STATE */
    
    ADD_STATE,
    CHANGE_STATE_NAME,
    CHANGE_STATE_POSITION,
    SET_INITIAL_STATE,
    SET_FINAL_STATE,
    DELETE_STATE,
    USER_CHANGED_STATE_POSITION,
    REMOVE_INITIAL_STATE,
    REMOVE_FINAL_STATE,
    
    /* TRANSITION */
    
    ADD_TRANSITION_FROM,
    ADD_TRANSITION_TO,
    ADD_TRANSITION,
    MOVE_TRANSITION_POSITION,
    CHANGE_TRANSITION_LABEL,
    DELETE_TRANSITION,
    SET_STRAIGHT_TRANSITION,
    SET_POLY_TRANSITION,
    SET_CURVE_TRANSITION,
    SET_BEZIER_TRANSITION,
    SET_SPLINE_TRANSITION,
    CHANGE_TRANSITION_LINE_TYPE,
    ADD_TRANSITION_CONTROL_POINT,
    CHANGE_TRANSITION_WEIGHT_LABEL,
    
    /* STORAGE_BUTTON */
    
    ADD_STATE_BUTTON,
    CONNECT_BUTTON,
    DELETE_BUTTON,
    FISHEYE_BUTTON,
    
    /* STORAGE_FILE */
    
    NEW_FILE,
    OPEN_FILE,
    CLOSE_FILE,
    SAVE_FILE,
    SAVE_FILE_AS,
    EXIT_VGI,
    
    /* STORAGE_EDIT */
    
    UNDO,
    REDO,
		SPRING_LAYOUT_PARAMETERS,
    
    /* STORAGE_VIEW */
    
    ACTUAL_SIZE,
    FIT_WINDOW,
    CENTER_GRAPH,
    ZOOM_IN,
    ZOOM_OUT,
    VIEW_AUTOMATON_PROP,
    VIEW_STATUS_BAR,
    
    /* STORAGE_LAYOUT */
    
    CIRCLE_LAYOUT,
		CIRCLE_LAYOUT_WO_ALG,
    GRID_LAYOUT,
    SPRING_LAYOUT,
    LINE_LAYOUT,
    GA_LAYERED_DRAWING_LAYOUT,
    LAYERED_LAYOUT,
    LAYERED_LATOUT_WITH_LEVELING,
    HIERARCHICAL_LAYOUT,
    HIERARCHICAL_LAYOUT2,
    FAST_ORGANIC,
    ORGANIC,
    SELF_ORGANIZING,
    
    /* STORAGE_ALGORITHM */
    
    //** BOOLEAN AUTOMATA **//
    
    B_ARE_EQUIVALENT,
    B_EVAL,
    B_IS_AMBIGUOUS,
    B_IS_COMPLETE,
    B_IS_DETERMINISTIC,
    B_IS_EMPTY,
    B_HAS_SUCC_COMP,
    B_IS_REALTIME,
    B_IS_STANDARD,
    B_ACCESSIBLE,
    B_EPS_REMOVAL,
    B_EPS_REMOVAL_SP,
    B_CO_ACCESSIBLE,
    B_COMPLETE,
    B_CONCATENATE,
    B_POWER,
    B_PRODUCT,
    B_QUOTIENT,
    B_REALTIME,
    B_STANDARDIZE,
    B_UNION_OF_STANDARD,
    B_CONCAT_OF_STANDARD,
    B_STAR_OF_STANDARD,
    B_UNION,
    B_TRANSPOSE,
    B_TRIM,
    B_COMPLEMENT,
    B_DETERMINIZE,
    B_MINIMIZE,
    B_MINIMIZE_MOORE,
    B_AUT_TO_EXP,
    B_DERIVED_TERM,
    B_EXP_TO_AUT,
    B_EXPAND,
    B_IDENTITY_EXP,
    B_STANDARD,
    B_THOMPSON,
    
    //** WEIGHTED AUTOMATA **//
    
    W_EVAL,
    W_IS_AMBIGUOUS,
    W_IS_COMPLETE,
    W_IS_EMPTY,
    W_HAS_SUCC_COMP,
    W_IS_REALTIME,
    W_IS_STANDARD,
    W_ACCESSIBLE,
    W_EPS_REMOVAL,
    W_EPS_REMOVAL_SP,
    W_CO_ACCESSIBLE,
    W_COMPLETE,
    W_CONCATENATE,
    W_POWER,
    W_PRODUCT,
    W_QUOTIENT,
    W_REALTIME,
    W_STANDARDIZE,
    W_UNION_OF_STANDARD,
    W_CONCAT_OF_STANDARD,
    W_STAR_OF_STANDARD,
    W_UNION,
    W_TRANSPOSE,
    W_TRIM,
    W_AUT_TO_EXP,
    W_DERIVED_TERM,
    W_EXP_TO_AUT,
    W_EXPAND,
    W_IDENTITY_EXP,
    W_STANDARD,
    W_THOMPSON,
    
    //** FMP TRANSDUCER **//
    
    T_IS_EMPTY,
    T_HAS_SUCC_COMP,
    T_IS_SUB_NORMALIZED,
    T_EPS_REMOVAL,
    T_EPS_REMOVAL_SP,
    T_DOMAIN,
    T_EVAL,
    T_EVAL_AUT,
    T_LTL_TO_PAIR,
    T_IMAGE,
    T_TRANSPOSE,
    T_TRIM,
    T_SUB_NORMALIZE,
    T_COMPOSITION_COVER,
    T_COMPOSITION_CO_COVER,
    T_COMPOSE,
    T_U_COMPOSE,
    T_TO_RW,
    T_INVERT,
    T_INTERSECTION,
    
    /* OTHERS */
    
    DELETE_CELLS,
    VALUETYPE_HAVE_BEEN_SET,
    TEST,
		GRAPH_GENERATOR,
    TEST_FUNCTION
}
