/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vjni_Vjni */

#ifndef _Included_vjni_Vjni
#define _Included_vjni_Vjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vjni_Vjni
 * Method:    boolAreEquivalent
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolAreEquivalent
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolEval
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_vjni_Vjni_boolEval
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIsAmbiquous
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolIsAmbiquous
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIsComplete
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolIsComplete
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIsDeterministic
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolIsDeterministic
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIsEmpty
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolIsEmpty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolHasSuccComp
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolHasSuccComp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIsRealtime
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolIsRealtime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIsStandard
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_boolIsStandard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolAccessible
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolAccessible
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolEpsRemoval
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolEpsRemoval
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolEpsRemovalSp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolEpsRemovalSp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolCoAccessible
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolCoAccessible
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolComplete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolComplete
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolConcatenate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolConcatenate
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolPower
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolPower
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolProduct
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolProduct
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolQuotient
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolQuotient
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolRealtime
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolRealtime
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolStandardize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolStandardize
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolUnionOfStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolUnionOfStandard
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolConcatOfStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolConcatOfStandard
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolStarOfStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolStarOfStandard
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolUnion
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolUnion
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolTranspose
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolTranspose
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolTrim
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolTrim
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolComplement
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolComplement
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolDeterminize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolDeterminize
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolMinimize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolMinimize
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolMinimizeMoore
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolMinimizeMoore
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolAutToExp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolAutToExp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolDerivedTerm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolDerivedTerm
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolExpToAut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolExpToAut
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolExpand
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolExpand
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolIdentityExp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolIdentityExp
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolStandard
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    boolThompson
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_boolThompson
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wEval
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_vjni_Vjni_wEval
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wIsAmbiguous
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_wIsAmbiguous
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wIsComplete
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_wIsComplete
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wIsEmpty
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_wIsEmpty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wHasSuccComp
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_wHasSuccComp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wIsRealtime
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_wIsRealtime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wIsStandard
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_wIsStandard
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wAccessible
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wAccessible
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wEpsRemoval
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wEpsRemoval
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wEpsRemovalSp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wEpsRemovalSp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wCoAccessible
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wCoAccessible
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wComplete
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wComplete
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wConcatenate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wConcatenate
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wPower
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wPower
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wProduct
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wProduct
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wQuotient
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wQuotient
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wRealtime
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wRealtime
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wStandardize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wStandardize
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wUnionOfStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wUnionOfStandard
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wConcatOfStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wConcatOfStandard
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wStarOfStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wStarOfStandard
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wUnion
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wUnion
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wTranspose
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wTranspose
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wTrim
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wTrim
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wAutToExp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wAutToExp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wDerivedTerm
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wDerivedTerm
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wExpToAut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wExpToAut
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wExpand
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wExpand
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wIdentityExp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wIdentityExp
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wStandard
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wStandard
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    wThompson
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_wThompson
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tIsEmpty
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_tIsEmpty
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tHasSuccComp
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_tHasSuccComp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tIsSubNormalized
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_vjni_Vjni_tIsSubNormalized
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tEpsRemoval
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tEpsRemoval
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tEpsRemovalSp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tEpsRemovalSp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tDomain
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tDomain
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tEval
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tEval
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tEvalAut
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tEvalAut
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tLtlToPair
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tLtlToPair
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tImage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tTranspose
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tTranspose
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tTrim
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tTrim
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tSubNormalize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tSubNormalize
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tCompositionCover
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tCompositionCover
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tCompositionCoCover
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tCompositionCoCover
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tCompose
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tCompose
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tUCompose
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tUCompose
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tToRw
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tToRw
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tInvert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tInvert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     vjni_Vjni
 * Method:    tIntersection
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_vjni_Vjni_tIntersection
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
