
import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * createAutomataDialog.java
 *
 * Created on 2011/12/10, 下午 01:12:26
 */
/**
 *
 * @author wkren
 */
public class CreateAutomataDialog extends javax.swing.JDialog {

    /** Creates new form createAutomataDialog */
    public CreateAutomataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SemiringTypeButtonGroup = new javax.swing.ButtonGroup();
        SemiringSetButtonGroup = new javax.swing.ButtonGroup();
        SemiringOperationButtonGroup = new javax.swing.ButtonGroup();
        MonoidTypeButtonGroup = new javax.swing.ButtonGroup();
        SemiringPanel = new javax.swing.JPanel();
        SemiringSymbolPanel = new javax.swing.JPanel();
        SemiringZeroSymbolLabel = new javax.swing.JLabel();
        semiringZeroSymbolTextField = new javax.swing.JTextField();
        semiringIdentitySymbolLabel = new javax.swing.JLabel();
        semiringIdentitySymbolTextField = new javax.swing.JTextField();
        SemiringTypePanel = new javax.swing.JPanel();
        NumericalRadioButton = new javax.swing.JRadioButton();
        SeriesRadioButton = new javax.swing.JRadioButton();
        SemiringSetPanel = new javax.swing.JPanel();
        BRadioButton = new javax.swing.JRadioButton();
        NRadioButton = new javax.swing.JRadioButton();
        ZRadioButton = new javax.swing.JRadioButton();
        QRadioButton = new javax.swing.JRadioButton();
        RRadioButton = new javax.swing.JRadioButton();
        CRadioButton = new javax.swing.JRadioButton();
        SemiringOperationPanel = new javax.swing.JPanel();
        ClassicalRadioButton = new javax.swing.JRadioButton();
        MinPlusRadioButton = new javax.swing.JRadioButton();
        MaxPlusRadioButton = new javax.swing.JRadioButton();
        MonoidPanel = new javax.swing.JPanel();
        SemiringSymbolPanel1 = new javax.swing.JPanel();
        monoidZeroSymbolLabel = new javax.swing.JLabel();
        monoidZeroSymbolTextField = new javax.swing.JTextField();
        MonoidTypePanel = new javax.swing.JPanel();
        UnitRadioButton = new javax.swing.JRadioButton();
        FreeRadioButton = new javax.swing.JRadioButton();
        ProductRadioButton = new javax.swing.JRadioButton();
        MonoidAlphabetPanel = new javax.swing.JPanel();
        monoidAlphabetComboBox = new javax.swing.JComboBox();
        SubAlphabetPanel = new javax.swing.JPanel();
        AddAlphabetButton1 = new javax.swing.JButton();
        delAlphabetButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        OkButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Type");

        SemiringPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Semiring"));
        SemiringPanel.setLayout(new java.awt.GridLayout(1, 0));

        SemiringSymbolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Symbol"));
        SemiringSymbolPanel.setLayout(new javax.swing.BoxLayout(SemiringSymbolPanel, javax.swing.BoxLayout.PAGE_AXIS));

        SemiringZeroSymbolLabel.setText("zero symbol:");
        SemiringSymbolPanel.add(SemiringZeroSymbolLabel);

        semiringZeroSymbolTextField.setText("0");
        SemiringSymbolPanel.add(semiringZeroSymbolTextField);

        semiringIdentitySymbolLabel.setText("identity symbol:");
        SemiringSymbolPanel.add(semiringIdentitySymbolLabel);

        semiringIdentitySymbolTextField.setText("1");
        SemiringSymbolPanel.add(semiringIdentitySymbolTextField);

        SemiringPanel.add(SemiringSymbolPanel);

        SemiringTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Type"));
        SemiringTypePanel.setLayout(new javax.swing.BoxLayout(SemiringTypePanel, javax.swing.BoxLayout.PAGE_AXIS));

        SemiringTypeButtonGroup.add(NumericalRadioButton);
        NumericalRadioButton.setText("numerical");
        NumericalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringTypeActionPerformed(evt);
            }
        });
        SemiringTypePanel.add(NumericalRadioButton);

        SemiringTypeButtonGroup.add(SeriesRadioButton);
        SeriesRadioButton.setText("series");
        SeriesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringTypeActionPerformed(evt);
            }
        });
        SemiringTypePanel.add(SeriesRadioButton);

        SemiringPanel.add(SemiringTypePanel);

        SemiringSetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Set"));
        SemiringSetPanel.setLayout(new javax.swing.BoxLayout(SemiringSetPanel, javax.swing.BoxLayout.PAGE_AXIS));

        SemiringSetButtonGroup.add(BRadioButton);
        BRadioButton.setText("B");
        BRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetActionPerformed(evt);
            }
        });
        SemiringSetPanel.add(BRadioButton);

        SemiringSetButtonGroup.add(NRadioButton);
        NRadioButton.setText("N");
        NRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetActionPerformed(evt);
            }
        });
        SemiringSetPanel.add(NRadioButton);

        SemiringSetButtonGroup.add(ZRadioButton);
        ZRadioButton.setText("Z");
        ZRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetActionPerformed(evt);
            }
        });
        SemiringSetPanel.add(ZRadioButton);

        SemiringSetButtonGroup.add(QRadioButton);
        QRadioButton.setText("Q");
        QRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetActionPerformed(evt);
            }
        });
        SemiringSetPanel.add(QRadioButton);

        SemiringSetButtonGroup.add(RRadioButton);
        RRadioButton.setText("R");
        RRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetActionPerformed(evt);
            }
        });
        SemiringSetPanel.add(RRadioButton);

        SemiringSetButtonGroup.add(CRadioButton);
        CRadioButton.setText("C");
        CRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringSetActionPerformed(evt);
            }
        });
        SemiringSetPanel.add(CRadioButton);

        SemiringPanel.add(SemiringSetPanel);

        SemiringOperationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));
        SemiringOperationPanel.setLayout(new javax.swing.BoxLayout(SemiringOperationPanel, javax.swing.BoxLayout.PAGE_AXIS));

        SemiringOperationButtonGroup.add(ClassicalRadioButton);
        ClassicalRadioButton.setText("classical");
        ClassicalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringOperationActionPerformed(evt);
            }
        });
        SemiringOperationPanel.add(ClassicalRadioButton);

        SemiringOperationButtonGroup.add(MinPlusRadioButton);
        MinPlusRadioButton.setText("minPlus");
        MinPlusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringOperationActionPerformed(evt);
            }
        });
        SemiringOperationPanel.add(MinPlusRadioButton);

        SemiringOperationButtonGroup.add(MaxPlusRadioButton);
        MaxPlusRadioButton.setText("maxPlus");
        MaxPlusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semiringOperationActionPerformed(evt);
            }
        });
        SemiringOperationPanel.add(MaxPlusRadioButton);

        SemiringPanel.add(SemiringOperationPanel);

        getContentPane().add(SemiringPanel, java.awt.BorderLayout.PAGE_START);

        MonoidPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Monoid"));
        MonoidPanel.setLayout(new java.awt.GridLayout(1, 0));

        SemiringSymbolPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Symbol"));
        SemiringSymbolPanel1.setLayout(new javax.swing.BoxLayout(SemiringSymbolPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        monoidZeroSymbolLabel.setText("zero symbol:");
        SemiringSymbolPanel1.add(monoidZeroSymbolLabel);

        monoidZeroSymbolTextField.setText("0");
        SemiringSymbolPanel1.add(monoidZeroSymbolTextField);

        MonoidPanel.add(SemiringSymbolPanel1);

        MonoidTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Type"));
        MonoidTypePanel.setLayout(new javax.swing.BoxLayout(MonoidTypePanel, javax.swing.BoxLayout.PAGE_AXIS));

        MonoidTypeButtonGroup.add(UnitRadioButton);
        UnitRadioButton.setText("unit");
        UnitRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monoidTypeActionPerformed(evt);
            }
        });
        MonoidTypePanel.add(UnitRadioButton);

        MonoidTypeButtonGroup.add(FreeRadioButton);
        FreeRadioButton.setText("free");
        MonoidTypePanel.add(FreeRadioButton);

        MonoidTypeButtonGroup.add(ProductRadioButton);
        ProductRadioButton.setText("product");
        MonoidTypePanel.add(ProductRadioButton);

        MonoidPanel.add(MonoidTypePanel);

        MonoidAlphabetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Alphabet"));
        MonoidAlphabetPanel.setLayout(new java.awt.GridLayout(1, 0));

        monoidAlphabetComboBox.setEditable(true);
        MonoidAlphabetPanel.add(monoidAlphabetComboBox);

        SubAlphabetPanel.setLayout(new java.awt.GridLayout(2, 1));

        AddAlphabetButton1.setText("add");
        AddAlphabetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monoidAlphabetAdd(evt);
            }
        });
        SubAlphabetPanel.add(AddAlphabetButton1);

        delAlphabetButton.setText("delete");
        delAlphabetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monoidDelAlphabetActionPerformed(evt);
            }
        });
        SubAlphabetPanel.add(delAlphabetButton);

        MonoidAlphabetPanel.add(SubAlphabetPanel);

        MonoidPanel.add(MonoidAlphabetPanel);

        getContentPane().add(MonoidPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(OkButton, java.awt.BorderLayout.EAST);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semiringTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semiringTypeActionPerformed
        this.SemiringSetPanel.setVisible(true);
        if (evt.getActionCommand().equals("numerical")) {
            semiringType = Semiring.SemiringType.NUMERICAL;
        }else if (evt.getActionCommand().equals("series")) {
            semiringType = Semiring.SemiringType.SERIES;
        }
    }//GEN-LAST:event_semiringTypeActionPerformed

    private void semiringSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semiringSetActionPerformed
        this.SemiringOperationPanel.setVisible(true);
        if (evt.getActionCommand().equals("B")) {
            semiringSet = Semiring.SemiringSet.B;
        }
        else if (evt.getActionCommand().equals("C")) {
            semiringSet = Semiring.SemiringSet.C;
        }
        else if (evt.getActionCommand().equals("N")) {
            semiringSet = Semiring.SemiringSet.N;
        }
        else if (evt.getActionCommand().equals("Q")) {
            semiringSet = Semiring.SemiringSet.Q;
        }
        else if (evt.getActionCommand().equals("R")) {
            semiringSet = Semiring.SemiringSet.R;
        }
        else if (evt.getActionCommand().equals("Z")) {
            semiringSet = Semiring.SemiringSet.Z;
        }
    }//GEN-LAST:event_semiringSetActionPerformed

    private void semiringOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semiringOperationActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("classical")) {
            semiringOperation = Semiring.SemiringOperation.CLASSICAL;
        }
        else if (evt.getActionCommand().equals("maxPlus")) {
            semiringOperation = Semiring.SemiringOperation.MAXPLUS;
        }
        else if (evt.getActionCommand().equals("minPlus")) {
            semiringOperation = Semiring.SemiringOperation.MINPLUS;
        }
    }//GEN-LAST:event_semiringOperationActionPerformed

    private void monoidTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monoidTypeActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("unit")) {
            monoidType = Monoid.MonoidType.unit;
        }
        else if (evt.getActionCommand().equals("free")) {
            monoidType = Monoid.MonoidType.free;
        }
        else if (evt.getActionCommand().equals("product")) {
            monoidType = Monoid.MonoidType.product;
        }
    }//GEN-LAST:event_monoidTypeActionPerformed

    private void monoidAlphabetAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monoidAlphabetAdd
        // TODO add your handling code here:
        monoidAlphabetComboBox.addItem(monoidAlphabetComboBox.getSelectedItem());
    }//GEN-LAST:event_monoidAlphabetAdd

    private void monoidDelAlphabetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monoidDelAlphabetActionPerformed
        // TODO add your handling code here:
        monoidAlphabetComboBox.removeItem(monoidAlphabetComboBox.getSelectedItem());
    }//GEN-LAST:event_monoidDelAlphabetActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        // TODO add your handling code here:
        Semiring semiring = new Semiring(semiringZeroSymbolTextField.getText(),
                                       semiringIdentitySymbolTextField.getText(),
                                       semiringType, semiringSet,
                                       semiringOperation, "", null, null);
        Monoid monoid = new Monoid(monoidZeroSymbolTextField.getText(), 
                                  monoidAlphabetComboBox.getModel().getSize(), 
                                  monoidAlphabetComboBox.getModel(), 
                                  0, null);
        this.setVisible(false);
    }//GEN-LAST:event_OkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAutomataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CreateAutomataDialog dialog = new CreateAutomataDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.SemiringSetPanel.setVisible(false);
                dialog.SemiringOperationPanel.setVisible(false);
                dialog.setVisible(true);
            }
        });
    }
    Semiring.SemiringType semiringType;
    Semiring.SemiringSet semiringSet;
    Semiring.SemiringOperation semiringOperation;
    Monoid.MonoidType monoidType;
    String semiringZeroSymbol;
    String semiringIdentitySymbol;
    String monoidZeroSymbol;
    ArrayList monoidAlphabet;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton AddAlphabetButton1;
    javax.swing.JRadioButton BRadioButton;
    javax.swing.JRadioButton CRadioButton;
    javax.swing.JRadioButton ClassicalRadioButton;
    javax.swing.JRadioButton FreeRadioButton;
    javax.swing.JRadioButton MaxPlusRadioButton;
    javax.swing.JRadioButton MinPlusRadioButton;
    javax.swing.JPanel MonoidAlphabetPanel;
    javax.swing.JPanel MonoidPanel;
    javax.swing.ButtonGroup MonoidTypeButtonGroup;
    javax.swing.JPanel MonoidTypePanel;
    javax.swing.JRadioButton NRadioButton;
    javax.swing.JRadioButton NumericalRadioButton;
    javax.swing.JButton OkButton;
    javax.swing.JRadioButton ProductRadioButton;
    javax.swing.JRadioButton QRadioButton;
    javax.swing.JRadioButton RRadioButton;
    javax.swing.ButtonGroup SemiringOperationButtonGroup;
    javax.swing.JPanel SemiringOperationPanel;
    javax.swing.JPanel SemiringPanel;
    javax.swing.ButtonGroup SemiringSetButtonGroup;
    javax.swing.JPanel SemiringSetPanel;
    javax.swing.JPanel SemiringSymbolPanel;
    javax.swing.JPanel SemiringSymbolPanel1;
    javax.swing.ButtonGroup SemiringTypeButtonGroup;
    javax.swing.JPanel SemiringTypePanel;
    javax.swing.JLabel SemiringZeroSymbolLabel;
    javax.swing.JRadioButton SeriesRadioButton;
    javax.swing.JPanel SubAlphabetPanel;
    javax.swing.JRadioButton UnitRadioButton;
    javax.swing.JRadioButton ZRadioButton;
    javax.swing.JButton cancelButton;
    javax.swing.JButton delAlphabetButton;
    javax.swing.JPanel jPanel1;
    javax.swing.JComboBox monoidAlphabetComboBox;
    javax.swing.JLabel monoidZeroSymbolLabel;
    javax.swing.JTextField monoidZeroSymbolTextField;
    javax.swing.JLabel semiringIdentitySymbolLabel;
    javax.swing.JTextField semiringIdentitySymbolTextField;
    javax.swing.JTextField semiringZeroSymbolTextField;
    // End of variables declaration//GEN-END:variables
}
