import com.mxgraph.model.mxCell;
import com.mxgraph.model.mxICell;
import com.mxgraph.view.mxGraph;
import javax.swing.JComboBox;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * state_properties.java
 *
 * Created on 2012/1/6, 下午 03:53:38
 */
/**
 *
 * @author bl606
 */
public class state_properties extends javax.swing.JPanel {

    /** Creates new form state_properties */
    public state_properties(mxGraph graph, mxCell cell) {
        _graph=graph;
        _cell=cell;
        Name = cell.getId();
        Style = cell.getStyle();
       
        Transition_from="no target";
        if(cell.getEdgeCount()!=0){
        Transition_from=cell.getEdgeAt(0).getTerminal(true).getId();
        }
        
        
        initComponents();
        
        
          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name_label = new javax.swing.JLabel();
        To_label = new javax.swing.JLabel();
        From_label = new javax.swing.JLabel();
        Iweight_label = new javax.swing.JLabel();
        Fweight_label = new javax.swing.JLabel();
        Style_label = new javax.swing.JLabel();
        Name_TextField = new javax.swing.JTextField();
        To_TextField = new javax.swing.JTextField();
        From_TextField = new javax.swing.JTextField();
        Initial_Weight_TextField = new javax.swing.JTextField();
        Final_weight_TextField = new javax.swing.JTextField();
        Style_ComboBox = new javax.swing.JComboBox();

        Name_label.setText("Name :");

        To_label.setText("Transition to :");

        From_label.setText("Transition from :");

        Iweight_label.setText("Initial weight :");

        Fweight_label.setText("Final weight :");

        Style_label.setText("Style :");

        Name_TextField.setText("state 0");
        Name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TextFieldActionPerformed(evt);
            }
        });

        To_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_TextFieldActionPerformed(evt);
            }
        });

        From_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                From_TextFieldActionPerformed(evt);
            }
        });

        Initial_Weight_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Initial_Weight_TextFieldActionPerformed(evt);
            }
        });

        Name_TextField.setText(Name);
        From_TextField.setText(Transition_from);
        Final_weight_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Final_weight_TextFieldActionPerformed(evt);
            }
        });

        Style_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELLIPSE", "RECTANGLE", "RHOMBUS", "CYLINDER", "ACTOR", "CLOUD", "TRIANGLE", "HEXAGON" }));
        Style_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Style_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(To_label)
                            .addComponent(Name_label)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Iweight_label)
                        .addComponent(From_label)
                        .addComponent(Fweight_label)
                        .addComponent(Style_label)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Style_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Final_weight_TextField)
                    .addComponent(Initial_Weight_TextField)
                    .addComponent(From_TextField)
                    .addComponent(To_TextField)
                    .addComponent(Name_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_label)
                    .addComponent(Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(To_label)
                    .addComponent(To_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(From_label)
                    .addComponent(From_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iweight_label)
                    .addComponent(Initial_Weight_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fweight_label)
                    .addComponent(Final_weight_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Style_label)
                    .addComponent(Style_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TextFieldActionPerformed
// TODO add your handling code here:
    Name = (String)Name_TextField.getText();
  
}//GEN-LAST:event_Name_TextFieldActionPerformed

private void Style_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Style_ComboBoxActionPerformed
// TODO add your handling code here:
    JComboBox cb = (JComboBox)evt.getSource();
    Style = "shape=" + ((String)cb.getSelectedItem()).toLowerCase();
    Object[] objects = new Object[1];
    objects[0]=_cell;
    System.out.print(Style);
    _graph.setCellStyle(Style, objects );
    
//    this.repaint();
//    System.out.println(_cell.getStyle());
}//GEN-LAST:event_Style_ComboBoxActionPerformed

private void To_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_TextFieldActionPerformed
// TODO add your handling code here:
    Transition_to = (String)To_TextField.getText();
}//GEN-LAST:event_To_TextFieldActionPerformed

private void From_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_From_TextFieldActionPerformed
// TODO add your handling code here:
    Transition_from = (String)From_TextField.getText();
}//GEN-LAST:event_From_TextFieldActionPerformed

private void Initial_Weight_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Initial_Weight_TextFieldActionPerformed
// TODO add your handling code here:
    Initial_weight = (String)Initial_Weight_TextField.getText();
}//GEN-LAST:event_Initial_Weight_TextFieldActionPerformed

private void Final_weight_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Final_weight_TextFieldActionPerformed
// TODO add your handling code here:
    Final_weight = (String)Initial_Weight_TextField.getText();
}//GEN-LAST:event_Final_weight_TextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Final_weight_TextField;
    private javax.swing.JTextField From_TextField;
    private javax.swing.JLabel From_label;
    private javax.swing.JLabel Fweight_label;
    private javax.swing.JTextField Initial_Weight_TextField;
    private javax.swing.JLabel Iweight_label;
    private javax.swing.JTextField Name_TextField;
    private javax.swing.JLabel Name_label;
    private javax.swing.JComboBox Style_ComboBox;
    private javax.swing.JLabel Style_label;
    private javax.swing.JTextField To_TextField;
    private javax.swing.JLabel To_label;
    // End of variables declaration//GEN-END:variables

    private String Name;
    private String Transition_to;
    private String Transition_from;
    private String Initial_weight;
    private String Final_weight;
    private String Style;
    private mxCell _cell;
    private mxGraph _graph;

}
